version: '3'

vars:
  SHELL: '{{if eq OS "windows"}}powershell {{end}}'

tasks:
  dev:
    cmds:
      - deno run serve

  build:
    cmds:
      - task: clean
      - deno run build

  clean:
    cmds:
      - '{{.SHELL}} rm -r _site/'